-- =====================================================
-- Migration 006: Scanner Telemetry Tables
-- =====================================================
-- Creates telemetry tables used by scanner + executor Phase 0 rollout:
--   1. scanner_runs
--   2. scanner_candidates
--   3. execution_attempts
-- =====================================================

-- =====================================================
-- 1. scanner_runs
-- One row per scanner invocation
-- =====================================================
CREATE TABLE IF NOT EXISTS scanner_runs (
    id UUID PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    duration_ms INTEGER,
    scan_mode TEXT NOT NULL DEFAULT 'scheduled',
    opportunities_found INTEGER NOT NULL DEFAULT 0,
    eligible_count INTEGER NOT NULL DEFAULT 0,
    watchlist_count INTEGER NOT NULL DEFAULT 0,
    diagnostics JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scanner_runs_started_at ON scanner_runs(started_at DESC);
CREATE INDEX IF NOT EXISTS idx_scanner_runs_mode ON scanner_runs(scan_mode);

-- =====================================================
-- 2. scanner_candidates
-- One row per candidate produced by scanner
-- =====================================================
CREATE TABLE IF NOT EXISTS scanner_candidates (
    id UUID PRIMARY KEY,
    scan_run_id UUID NOT NULL REFERENCES scanner_runs(id) ON DELETE CASCADE,
    network TEXT,
    token_pair TEXT,
    buy_dex TEXT,
    sell_dex TEXT,
    spread_pct NUMERIC(18, 8),
    est_net_profit NUMERIC(24, 8),
    quote_timestamp TIMESTAMPTZ,
    data_source TEXT,
    status TEXT NOT NULL DEFAULT 'scanned',
    opportunity_payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scanner_candidates_scan_run_id ON scanner_candidates(scan_run_id);
CREATE INDEX IF NOT EXISTS idx_scanner_candidates_network ON scanner_candidates(network);
CREATE INDEX IF NOT EXISTS idx_scanner_candidates_quote_ts ON scanner_candidates(quote_timestamp DESC);

-- =====================================================
-- 3. execution_attempts
-- One row per bundle submission/execution decision
-- =====================================================
CREATE TABLE IF NOT EXISTS execution_attempts (
    id UUID PRIMARY KEY,
    candidate_id UUID REFERENCES scanner_candidates(id) ON DELETE SET NULL,
    scan_run_id UUID REFERENCES scanner_runs(id) ON DELETE SET NULL,
    submitted_at TIMESTAMPTZ,
    target_block BIGINT,
    bundle_hash TEXT,
    included BOOLEAN,
    failure_reason TEXT,
    realized_net_profit NUMERIC(24, 8),
    latency_ms INTEGER,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_execution_attempts_candidate_id ON execution_attempts(candidate_id);
CREATE INDEX IF NOT EXISTS idx_execution_attempts_scan_run_id ON execution_attempts(scan_run_id);
CREATE INDEX IF NOT EXISTS idx_execution_attempts_submitted_at ON execution_attempts(submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_execution_attempts_included ON execution_attempts(included);
CREATE INDEX IF NOT EXISTS idx_execution_attempts_failure_reason ON execution_attempts(failure_reason);

-- Enable RLS and keep permissive policy for now to match existing project defaults.
ALTER TABLE scanner_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE scanner_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE execution_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all access to scanner_runs" ON scanner_runs;
CREATE POLICY "Allow all access to scanner_runs" ON scanner_runs
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to scanner_candidates" ON scanner_candidates;
CREATE POLICY "Allow all access to scanner_candidates" ON scanner_candidates
    FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow all access to execution_attempts" ON execution_attempts;
CREATE POLICY "Allow all access to execution_attempts" ON execution_attempts
    FOR ALL USING (true) WITH CHECK (true);

COMMENT ON TABLE scanner_runs IS 'Scanner run-level telemetry';
COMMENT ON TABLE scanner_candidates IS 'Opportunity candidates generated by each scanner run';
COMMENT ON TABLE execution_attempts IS 'Execution attempts linked to scanner candidates';
